### ISSUE TITLE
Async/parallelize image generation 

### ISSUE THREAD

**Issue by AI-Spawn** [AI-Spawn/Auto-Lip-Sync#21]
Video generation can be sped up dramatically if the generation of images in run in parallel.

**Comment by Yey007** [comment]
Not sure how useful `asyncio`/async/await will be but the `threading` module definitely sounds like it would help here.

**Comment by AI-Spawn** [comment]
Currently I'm looking at either asyncio or multiprocessing. From what I've read (and there's a good chance I'm wrong about this) asyncio/mp work much better for pypy. The majority of the time currently comes from image generation but in the future if I want to min-max everything then I might set it up for that.

**Comment by Yey007** [comment]
I have no knowledge of PyPy so do whatever you need on that front. However, I don't quite understand what you mean by "min-max" everything.

**Comment by AI-Spawn** [comment]
#24
