### ISSUE TITLE
Each Pose should be able to set custom a closed mouth

### ISSUE THREAD

**Issue by MrBreadWater** [AI-Spawn/Auto-Lip-Sync#37]
For instance a smile if happy. 

As a side note, it looks a bit odd/jerky when there are small pauses between words, going between default pose and another

**Comment by AI-Spawn** [comment]
You are absolutely 100% correct and I don't know why I didn't think to do this

**Comment by AI-Spawn** [comment]
Thanks for the suggestion. Completed in #40. In a pose in `characters.json`, you can add `"closed_mouth"`and set it to be the name of an image in your mouths folder. 

For example:
```json
 "happy": {
    "image": "char_happy.png",
    "x": 103,
    "x": 103,
    "y": 199,
    "closed_mouth": "smile.png"
  },
```
